services:
  store_manager:
    build: .
    volumes:
      - .:/app
    depends_on:
      - mysql
      - redis
    networks:
      - labo02-network

  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: labo02_db
      MYSQL_USER: labo02
      MYSQL_PASSWORD: labo02
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - labo02-network

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - labo02-network

networks:
  labo02-network:
    external: true
    
volumes:
  mysql_data:
