name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dépot
        uses: actions/checkout@v4

      - name: Créer fichier .env (TODO - utilisez les secrets)
        run: |
          echo "DB_HOST=mysql" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_NAME=labo02_db" >> .env
          echo "DB_USER=labo02" >> .env
          echo "DB_PASS=labo02" >> .env
          echo "REDIS_HOST=redis" >> .env
          echo "REDIS_PORT=6379" >> .env
          echo "REDIS_DB=0" >> .env

      - name: Démarrer le conteneur
        run: |
          docker network create labo02-network
          docker compose up -d

      - name: Attendre MySQL
        run: |
          sleep 10
          timeout=60
          until docker exec mysql mysqladmin ping -h localhost -u root -proot --silent; do
            echo "Waiting for MySQL..."
            sleep 3
            timeout=$((timeout - 3))
            if [ $timeout -le 0 ]; then
              echo "MySQL failed to start"
              exit 1
            fi
          done
          sleep 5

      - name: Éxécuter les tests
        run: docker exec store_manager_cli pytest

      - name: Cleanup
        if: always()
        run: docker compose down -v